[package]
name = "exst_repl"
version = "0.1.0"
authors = ["ryoto naruse <naruse.com@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exst_core = { path = "../exst_core" }
clap = "2.33.1"
