[package]
name = "exst_base_cmd"
version = "0.1.0"
authors = ["ryoto naruse <naruse.com@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
